### ISSUE TITLE
Compiled files wont run

### ISSUE THREAD

**Issue by tilk48** [chgibb/hydro-sdk#51]
Hey, I just wrote a typescript file and compiled as usual but when I tried to run it in app I got the following error:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building RunFromNetwork(dirty, state:
_RunFromNetwork#39461):
Closure call with mismatched arguments: function 'dispatch'
Receiver: Closure: (List<dynamic>) => Null
Tried calling: dispatch(Instance(length:0) of '_GrowableList', parentState: Instance of
'HydroState')
Found: dispatch(List<dynamic>) => Null
The relevant error-causing widget was:
  RunFromNetwork 
lib/main.dart:46
When the exception was thrown, this was the stack:
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
#1      _RunFromNetwork.build 
package:hydro_sdk/runFromNetwork.dart:295
#2      StatefulElement.build 
package:flutter/…/widgets/framework.dart:4663
#3      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4546
#4      StatefulElement.performRebuild 
package:flutter/…/widgets/framework.dart:4719
#5      Element.rebuild 
package:flutter/…/widgets/framework.dart:4262
#6      BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2667
#7      WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:866
#8      RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:286
#9      SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1117
#10     SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:1056
#11     SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:972
#15     _invoke  (dart:ui/hooks.dart:253:10)
#16     _drawFrame  (dart:ui/hooks.dart:211:3)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Even the most simple file wont run, it dosent matter if the file uses host args or not. I didnt pass in any arguments but doing so also make a difference I also tried it with various examples, including the [hostArgs](https://github.com/chgibb/hydro-sdk/blob/master/examples/hostArgs/index.ts) file but got the same results.

Already compiled files work perfectly fine though, indicating a problem with the compiler. The exact command I use was as follows:
`node node_modules/hydro-sdk/dist/compiler -t step.ts -m step -d assets -p debug`

Switching to production mode made no difference.

Here are example files that caused issues for me (github only allows zips):
[Archiv.zip](https://github.com/chgibb/hydro-sdk/files/5103682/Archiv.zip)

**Comment by chgibb** [comment]
I've managed to repro with the following:
```
I/flutter (21550): I/Hydro 0 native, 139 virtual prototypes
I/flutter (21550): attempt to call a nil value null with []
I/flutter (21550): Error raised in:
I/flutter (21550):   require
I/flutter (21550):      defined in main_chunk:0
I/flutter (21550): VM stacktrace follows:
I/flutter (21550): @.hydroc/78f6e3c3677c51dce6d68725bbd71bcfc3fdd3b74515877f9d5ec7ffc541faf5/step:4
I/flutter (21550):   (_Lmain_chunk::d71c39187689639986b4a58c858b8f43c02ed5546a801bc21b68dbaea44632b1::require::file::0)
I/flutter (21550): @.hydroc/78f6e3c3677c51dce6d68725bbd71bcfc3fdd3b74515877f9d5ec7ffc541faf5/step:1521
I/flutter (21550):   (null)
I/flutter (21550): Dart stacktrace follows:
I/flutter (21550): #0      Thread.attemptCall 
package:hydro_sdk/…/thread/thread.dart:36
I/flutter (21550): #1      tailcall 
package:hydro_sdk/…/instructions/tailcall.dart:24
I/flutter (21550): #2      Frame.cont 
package:hydro_sdk/…/vm/frame.dart:276
I/flutter (21550): #3      call 
package:hydro_sdk/…/instructions/call.dart:22
I/flutter (21550): #4      Frame.cont 
package:hydro_sdk/…/vm/frame.dart:271
I/flutter (21550): #5      Closure._dispatch 
package:hydro_sdk/…/vm/closure.dart:96
I/flutter (21550): #6      Closure.dispatch 
package:hydro_sdk/…/vm/closure.dart:83
I/flutter (21550): #7      HydroFunctionImpl.pcall 
package:hydro_sdk/hydroState.dart:27
I/flutter (21550): #8      HotReloadable.fullRestart.<a

════════ Exception caught by widgets library ═══════════════════════════════════
The following NoSuchMethodError was thrown building RunFromNetwork(dirty, state: _RunFromNetwork#69868):
Closure call with mismatched arguments: function 'dispatch'
Receiver: Closure: (List<dynamic>) => Null
Tried calling: dispatch(Instance(length:0) of '_GrowableList', parentState: Instance of 'HydroState')
Found: dispatch(List<dynamic>) => Null

The relevant error-causing widget was
    RunFromNetwork 
lib/main.dart:7
When the exception was thrown, this was the stack
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
#1      _RunFromNetwork.build 
package:hydro_sdk/runFromNetwork.dart:295
#2      StatefulElement.build 
package:flutter/…/widgets/framework.dart:4619
#3      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4502
#4      StatefulElement.performRebuild 
package:flutter/…/widgets/framework.dart:4675
...
```
Looking at the VM stacktrace: `@.hydroc/78f6e3c3677c51dce6d68725bbd71bcfc3fdd3b74515877f9d5ec7ffc541faf5/step:4` is the return statement in `step.hc`'s `require` function. TS `import`s are mapped into calls to `require` whose implementation is injected by the bundler. `@.hydroc/78f6e3c3677c51dce6d68725bbd71bcfc3fdd3b74515877f9d5ec7ffc541faf5/step:1521` is the `import {runApp} from "hydro-sdk/runtime/flutter/runApp";` statement. Looking at the (pre-bytecode compiled) Lua bundle, it looks like nothing from `hydro-sdk/` is being included by the bundler. I need to keep digging.

**Comment by chgibb** [comment]
In #40 , I introduced a test to build the example project. It never tries to run the output. I think if the output was run in that test, this could have been caught earlier. Still digging for root cause.

**Comment by chgibb** [comment]
It looks like TSTL is failing to resolve require paths for imports into node_modules. Inside the top level of the hydro repo, everything is imported with relative paths. That's probably why this has never come up before. I think a solution to this in the compiler could be to use `tstl.transpileString`, use the Typescript compiler API to resolve imports and then transform TSTL's output by rewriting require paths to the hash of their resolved import. This will likely take some time to implement.

**Comment by tilk48** [comment]
Ok good to know that you have an idea where this is coming from. Is there any temporary work around to make runnable files?
Let me know if I can help you with this in any way.

**Comment by chgibb** [comment]
I've almost finished implementing the approach I described above in this branch https://github.com/chgibb/hydro-sdk/tree/51

**Comment by chgibb** [comment]
I'm not sure if what I described previously will work. TSTL performs some minor type-directed emit (like transforming certain TS language features into calls to helpers). It needs visibility into the type information of imported symbols in a given module in order to do that. A half dozen or so tests in the branch I linked are broken because of malformed type-directed emit in some cases.

**Comment by chgibb** [comment]
@tilk48 I think a work around for now could be to use relative imports into node_modules. There's some old discussion on the TSTL repo about module resolution. I'll open an issue there.

**Comment by chgibb** [comment]
On further investigation, I've opted not to open an issue with TSTL. It looks like rather than simply not resolving paths into `node_modules`, TSTL simply never performs transpilation for paths contained in `node_modules`. Critically, however it will still perform type directed emit of files not within `node_modules` based on type information from files within `node_modules`. I think a solution could be to ship pre-compiled Lua on Hydro's end, and special case the bundler to import it at build time.

**Comment by chgibb** [comment]
@tilk48 this should be fixed on `master` now. Deleting your `package-lock.json`, `node_modules`, and re running `npm install` should get you the latest code with the fix. A test for this scenario is pending on #52  as well.

**Comment by chgibb** [comment]
@tilk48 this should be corrected now. If not, please feel free to reopen.

**Comment by tilk48** [comment]
Hey, thanks for keeping me up to date with progress you made on this issue! Sadly I have to reopen this because the error still occurs on my side. I made sure to have the latest version installed. Since the compiled files are larger now I think its safe to assume that the update was applied.
When I try to compile the file I send you when opening the issue I get the following error on run time:

```
HydroError (attempt to call a nil value null with []
VM stacktrace follows:
@.hydroc/3b4f4069602ab14c98dbe6eee975bf85578537c28190146be877006c2fb6b03c/step:4
  (null)
Dart stacktrace follows:
#0      Thread.attemptCall (package:hydro_sdk/cfr/thread/thread.dart:36:7)
#1      tailcall (package:hydro_sdk/cfr/vm/instructions/tailcall.dart:24:28)
#2      Frame.cont (package:hydro_sdk/cfr/vm/frame.dart:276:21)
#3      call (package:hydro_sdk/cfr/vm/instructions/call.dart:22:17)
#4      Frame.cont (package:hydro_sdk/cfr/vm/frame.dart:271:21)
#5      Closure._dispatch (package:hydro_sdk/cfr/vm/closure.dart:96:11)
#6      Closure.dispatch (package:hydro_sdk/cfr/vm/closure.dart:83:14)
#7      HydroFunctionImpl.pcall (package:hydro_sdk/hydroState.dart:27:25)
#8      HotReloadable.fullRestart.<anonymous closure>.<anonymous closure> (package:hydro_sdk/cfr/hotReloadable.dart:80:20)
#9      State.setState (package:flutter/src/widgets/framework.dart:1240:30)
#10     HotReloadable.fullRestart.<anonymous closure> (package:hydro_sdk/cfr/hotReloadable.dart:78:7)
<asynchronous suspension>
#11     HotReloadable.fullRestart.<anonymous closure> (package:hydro_sdk/cfr/hotReloadable.dart)
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#17     Future._complete (dart:async/future_impl.dart:519:7)
#18     new Future.delayed.<anonymous closure> (dart:async/future.dart:322:16)
#19     _rootRun (dart:async/zone.dart:1182:47)
#20     _CustomZone.run (dart:async/zone.dart:1093:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#23     _rootRun (dart:async/zone.dart:1190:13)
#24     _CustomZone.run (dart:async/zone.dart:1093:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#26     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#27     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#28     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
)
```
I used the same compile command as last time and tested it in debug and release mode. Can you reproduce this or does this only happen on my machine?
Thank you for your time and once again if I can anything to help please let me know

**Comment by tilk48** [comment]
I cant reopen because you closed it.

**Comment by chgibb** [comment]
No, thank you for your time! I really appreciate the interest you're showing in this project! How are you running `step.ts`? Do you have a public repository that reproduces the issue you're seeing?

**Comment by tilk48** [comment]
I have made this minimal repository which reproduces the error on my side: https://github.com/tilk48/hydro_test_env
While I tested the repository I noticed something very strange though. The `step.ts` file is in the root as well as in` assets/`, to me they look exactly similar but when I compile the one in root with this command: `node node_modules/hydro-sdk/dist/compiler -t step.ts -m step -d assets -p debug` the file size is 95kb and I get the following (new) error on runtime:
```
The following message was thrown building RunFromNetwork(dirty, state: _RunFromNetwork#0f41b):
Dispatched function prototypes are required to have debug symbols but the prototype from 1909-1928
in @.hydroc/78f6e3c3677c51dce6d68725bbd71bcfc3fdd3b74515877f9d5ec7ffc541faf5/step could not be
matched to a debug symbol
The relevant error-causing widget was:
  RunFromNetwork 
lib/main.dart:46
When the exception was thrown, this was the stack:
#0      Closure.maybeLookupReloadedPrototype 
package:hydro_sdk/…/vm/closure.dart:40
#1      Closure.dispatch 
package:hydro_sdk/…/vm/closure.dart:64
#2      _RunFromNetwork.build 
package:hydro_sdk/runFromNetwork.dart:295
#3      StatefulElement.build 
package:flutter/…/widgets/framework.dart:4663
#4      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4546
#5      StatefulElement.performRebuild 
package:flutter/…/widgets/framework.dart:4719
#6      Element.rebuild 
package:flutter/…/widgets/framework.dart:4262
#7      BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2667
#8      WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:866
#9      RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:286
#10     SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1117
#11     SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:1056
#12     SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:972
#16     _invoke  (dart:ui/hooks.dart:253:10)
#17     _drawFrame  (dart:ui/hooks.dart:211:3)
(elided 3 frames from dart:async)
```

But when I compile the on in `assets/` with this command: `node node_modules/hydro-sdk/dist/compiler -t assets/step.ts -m step -d assets -p debug` the generated file is 119kb and I get the "old" error I described earlier.
